### PR TITLE
Fix custom annotation of breakends and non-supported SVs (exact mode)

### LINKED ISSUE #1397: --custom with 'exact' returns multiple values for structural variant
VEP sometimes returns multiple `--custom` annotations when running with the `exact` annotation type.

Input GRCh38 variants:
```
chr11   99819752        MantaBND:2716:0:1:0:0:0:0       C       CAACTGAG]chr11:99820576]        892     PASS    SVTYPE=BND;MATEID=MantaBND:2716:0:1:0:0:0:1;SVINSLEN=7;SVINSSEQ=AACTGAG;BND_DEPTH=266;MATE_BND_DEPTH=24;AC=3;AN=6       GT    0/1
chr11   99820576        MantaBND:2716:0:1:0:0:0:1       C       CCTCAGTT]chr11:99819752]        892     PASS    SVTYPE=BND;MATEID=MantaBND:2716:0:1:0:0:0:0;SVINSLEN=7;SVINSSEQ=CTCAGTT;BND_DEPTH=24;MATE_BND_DEPTH=266;AC=3;AN=6       GT    0/1
```

Relevant VEP argument:
```
--custom" "<cut>/gnomad.genomes.v3.1.2.sites.stripped.vcf.gz,gnomAD,vcf,exact,0,AF,HN
```
Resource with index can be downloaded [here](https://downloads.molgeniscloud.org/downloads/vip/resources/GRCh38/gnomad.genomes.v3.1.2.sites.stripped.vcf.gz) and [here](https://downloads.molgeniscloud.org/downloads/vip/resources/GRCh38/gnomad.genomes.v3.1.2.sites.stripped.vcf.gz.csi)

Relevant content of this file:
```
chr11   99819752        .       C       CAACTGAGGAACCAGGCATTA   .       .       AF=1.97571e-05;HN=0
chr11   99819752        .       C       CAACTGAGGAACCAGGCATTATT .       .       AF=3.29264e-05;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTG        .       .       AF=7.92257e-05;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGA    .       .       AF=0.000112251;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGAATG .       .       AF=0.00129216;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGAATGATAAAG   .       .       AF=0.000462779;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGAATGATAAAGACTGATGGGGGAATA    .       .       AF=0.000132079;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGAATGATAAAGACTGATGGGGGAGTA    .       .       AF=9.24361e-05;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGAATGATAAAGACTGATGGGGGAGTAATA .       .       AF=0.000217992;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGAATGATAAAGACTGATGGGGGAGTAATAATTCTG   .       .       AF=0.000145291;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGAATGATAAAGACTGATGGGGGATTAATA .       .       AF=6.60083e-06;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGAATGATAAAGATTG       .       .       AF=8.58414e-05;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGAATGATAAAGATTGATGGGGG        .       .       AF=0.000125457;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGAATGATAAAGATTGATGGGGGA       .       .       AF=0.000204712;HN=0
chr11   99820576        .       C       CCTCAGTTGGCATCTGAGGAATGATAAAGATTGATGGGGGAATA    .       .       AF=0.00026418;HN=0
```

Output:
```
chr11   99819752        MantaBND:2716:0:1:0:0:0:0       C       CAACTGAG]chr11:99820576]        892     PASS    SVTYPE=BND;MATEID=MantaBND:2716:0:1:0:0:0:1;SVINSLEN=7;SVINSSEQ=AACTGAG;BND_DEPTH=266;MATE_BND_DEPTH=24;AC=3;AN=6;CSQ=CAACTGAG]chr11|coding_sequence_variant|MODIFIER|CNTN5|53942|Transcript|NM_001243270.2|protein_coding|3/24||||657/6360|265/3303|89/1100||||1||1|||EntrezGene|||||||||||||||||||||||||||||||||||||||||||5.56599998474121|chr11:99819753-99819753&chr11:99819753-99819753|1.97571e-05&3.29264e-05|0&0||||,CAACTGAG]chr11|coding_sequence_variant|MODIFIER|CNTN5|53942|Transcript|NM_001243271.2|protein_coding|4/21||||796/4495|265/2736|89/911||||1||1|||EntrezGene|||||||||||||||||||||||||||||||||||||||||||5.56599998474121|chr11:99819753-99819753&chr11:99819753-99819753|1.97571e-05&3.29264e-05|0&0||||,CAACTGAG]chr11|coding_sequence_variant|MODIFIER|CNTN5|53942|Transcript|NM_014361.4|protein_coding|4/25||||796/6499|265/3303|89/1100||||1||1||1|EntrezGene|||||||||||||||||||||||||||||||||||||||||||5.56599998474121|chr11:99819753-99819753&chr11:99819753-99819753|1.97571e-05&3.29264e-05|0&0||||,CAACTGAG]chr11|intron_variant|MODIFIER|CNTN5|53942|Transcript|NM_175566.2|protein_coding||1/21|||||||||1||1|||EntrezGene|||||||||||||||||||||||||||||||||||||||||||5.56599998474121|chr11:99819753-99819753&chr11:99819753-99819753|1.97571e-05&3.29264e-05|0&0||||      GT       0/1
chr11   99820576        MantaBND:2716:0:1:0:0:0:1       C       CCTCAGTT]chr11:99819752]        892     PASS    SVTYPE=BND;MATEID=MantaBND:2716:0:1:0:0:0:0;SVINSLEN=7;SVINSSEQ=CTCAGTT;BND_DEPTH=24;MATE_BND_DEPTH=266;AC=3;AN=6;CSQ=CCTCAGTT]chr11|intron_variant|MODIFIER|CNTN5|53942|Transcript|NM_001243270.2|protein_coding||3/23|||||||||1||1|||EntrezGene|||||||||||||||||||||||||||||||||||||||||||-0.967999994754791|chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577|7.92257e-05&0.000112251&0.00129216&0.000462779&0.000132079&9.24361e-05&0.000217992&0.000145291&6.60083e-06&8.58414e-05&0.000125457&0.000204712&0.00026418&0.000527241|0&0&0&0&0&0&0&0&0&0&0&0&0&0||||,CCTCAGTT]chr11|intron_variant|MODIFIER|CNTN5|53942|Transcript|NM_001243271.2|protein_coding||4/20|||||||||1||1|||EntrezGene|||||||||||||||||||||||||||||||||||||||||||-0.967999994754791|chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577|7.92257e-05&0.000112251&0.00129216&0.000462779&0.000132079&9.24361e-05&0.000217992&0.000145291&6.60083e-06&8.58414e-05&0.000125457&0.000204712&0.00026418&0.000527241|0&0&0&0&0&0&0&0&0&0&0&0&0&0||||,CCTCAGTT]chr11|intron_variant|MODIFIER|CNTN5|53942|Transcript|NM_014361.4|protein_coding||4/24|||||||||1||1||1|EntrezGene|||||||||||||||||||||||||||||||||||||||||||-0.967999994754791|chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577|7.92257e-05&0.000112251&0.00129216&0.000462779&0.000132079&9.24361e-05&0.000217992&0.000145291&6.60083e-06&8.58414e-05&0.000125457&0.000204712&0.00026418&0.000527241|0&0&0&0&0&0&0&0&0&0&0&0&0&0||||,CCTCAGTT]chr11|intron_variant|MODIFIER|CNTN5|53942|Transcript|NM_175566.2|protein_coding||1/21|||||||||1||1|||EntrezGene|||||||||||||||||||||||||||||||||||||||||||-0.967999994754791|chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577&chr11:99820577-99820577|7.92257e-05&0.000112251&0.00129216&0.000462779&0.000132079&9.24361e-05&0.000217992&0.000145291&6.60083e-06&8.58414e-05&0.000125457&0.000204712&0.00026418&0.000527241|0&0&0&0&0&0&0&0&0&0&0&0&0&0||||     GT       0/1
```
Which now contains:
``` 
gnomAD     chr11:99819753-99819753&chr11:99819753-99819753
gnomAD_AF  1.97571e-05&3.29264e-05
gnomAD_HN  0&0
```

This causes issues with our downstream tooling expects zero/one annotation values for any given chrom/pos/ref/alt.

This doesn't appear to me as an `exact` match as described [here](https://grch37.ensembl.org/info/docs/tools/vep/script/vep_custom.html). I would have expected zero annotations for these two records since the ALT doesn't exactly match.

### PR DESCRIPTION
**Pull request by nuno-agostinho**
ENSVAR-5610, fixes #1397

### Changelog

- Custom exact matching improvements:
  - Avoid matching breakpoints with SNPs when using custom annotation in exact mode
  - Only perform this check when using custom annotation in VCF format (other formats do not contain variant type information in a standardised way)
- Bug fix: avoid skipping all subsequent SVs after skipping one
- Improvements to warning messages thrown when skipping variants:
  - Warn when skipping any non-supported SV type
  - Trim input whitespaces to improve readability of messages
  - Bug fix: avoid calling `skipped_variant_msg()` with ensembl-io's parser

### Documentation

- Updates to public documentation: https://github.com/Ensembl/public-plugins/pull/722

### Testing

Run VEP with custom annotation in exact mode containing breakends and `NON_REF` SVs, such as:

```
1   2642609        .                               G  A  .  .  .  .  .
1 2642609   nonREF  G  <NON_REF>  892  PASS  AN=6  GT  0/1
chr11   99819752        nonREF       C       <NON_REF>        892     PASS    AN=6       GT    0/1
1       713044  DUP1     C       <CN=2>  .       .       END=755966
1       713044  DUP2     C       <CN2>  .       .       END=755966
1       713044  DUP2     C       <INS:FHJDSJH>  .       .       END=755966
chr11   99819752        MantaBND:2716:0:1:0:0:0:0       C       CAACTGAG]chr11:99820576]        892     PASS    SVTYPE=BND;MATEID=MantaBND:2716:0:1:0:0:0:1;SVINSLEN=7;SVINSSEQ=AACTGAG;BND_DEPTH=266;MATE_BND_DEPTH=24;AC=3;AN=6       GT    0/1
chr11   99820576        MantaBND:2716:0:1:0:0:0:1       C       CCTCAGTT]chr11:99819752]        892     PASS    SVTYPE=BND;MATEID=MantaBND:2716:0:1:0:0:0:0;SVINSLEN=7;SVINSSEQ=CTCAGTT;BND_DEPTH=24;MATE_BND_DEPTH=266;AC=3;AN=6       GT    0/1
```

Run VEP using a command such as:
```
gnomAD=input/gnomad.genomes.v3.1.2.sites.stripped.vcf.gz
vep --i $vcf --vcf --database --custom $gnomAD,gnomAD,vcf,exact,0,AF,HN
```

Output should not contain custom annotation for NON_REF and breakend variants.

### CODE REVIEW

File: modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm [hunk 1]
```diff
@@ -458,19 +456,9 @@ sub _record_overlaps_VF {
...
 
-  # match on variant class (if enabled)
-  # confounded by different descriptions for the same event
-  if ($same_type) {
-    my $vf_class = $vf->class_SO_term;
-    my $ref_class = get_SO_term($parser);
-
-    return 0 if defined $ref_class && defined $vf_class && $ref_class ne $vf_class;
-  }
-
```
Comment (nakib103) [inline modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:473]: We should keep this for robustness. Although it generally does not happen for other case than `BND` generally but think of a case like -
`chr11 99819752 test_sv C <INS> 892 PASS SVTYPE=BND;END=99819752`

The parser return `start=99819753` (which obviously is wrong for SV) and does not match the gnomAD SNP, but if we get non-usual case like this -
`chr11 99819751 test_sv C <INS> 892 PASS SVTYPE=BND;END=99819752`

It will match!

File: modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm [hunk 2]
```diff
@@ -328,12 +329,28 @@ sub _record_overlaps_VF {
...
+  # match records based on variant class (if enabled)
+  my $ref_class = get_SO_term($parser);
+
+  # avoid matching breakpoints (start == end) with SNPs in exact mode
+  my $vf_class  = $vf->class_SO_term;
+  my $is_exact_breakpoint = $type eq 'exact' && defined $vf_class && $vf_class =~ /breakpoint/;
+
+  if ($same_type || $is_exact_breakpoint) {
+    # do not match if only one of the types is defined
+    return 0 if defined $ref_class xor defined $vf_class;
```
Comment (nakib103) [inline modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm:345]: This is redundant with the next check as it makes sure both are defined.
```suggestion
```

**Review by nakib103 — CHANGES_REQUESTED** [review]

File: modules/Bio/EnsEMBL/VEP/Parser.pm [hunk 3]
```diff
@@ -685,7 +682,12 @@ sub get_SO_term {
     BND  => 'chromosome_breakpoint'
   );
 
-  return $terms{$abbrev};
+  my $res = $terms{$abbrev};
+  ## unsupported SV types
+  if ($self->isa('Bio::EnsEMBL::VEP::Parser')) {
+    $self->skipped_variant_msg("$abbrev type is not supported") unless $res;
+  }
```
[the remark this answers is not in the document]
Comment (nuno-agostinho) [reply modules/Bio/EnsEMBL/VEP/Parser.pm:689]: Hey Nakib! We only use ensembl-io directly for reading custom annotation: this means we will warn the user about the multiple types of variants that are skipped in custom annotation. Is this information useful by default or just noise?

What about if it's only printed for custom annotation if using `--verbose`? Something like:

```suggestion
  ## unsupported SV types
  if ($self->param('verbose') || $self->isa('Bio::EnsEMBL::VEP::Parser')) {
    Bio::EnsEMBL::VEP::Parser->skipped_variant_msg("$abbrev type is not supported") unless $res;
  }
```

File: modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm (hunk 2 above)
Comment (nuno-agostinho) [reply modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm:345]: This is not redundant:
- The other check only returns 0 if both variables are defined and not equal.
- If one is defined but the other is not, then they are not equal, and should also return 0. This check is required for this condition.

File: modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm (hunk 1 above)
Comment (nuno-agostinho) [reply modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:473]: Hey Nakib, I simply moved this from `File.pm` to `File/VCF.pm` because this can only be done for custom VCF files (other custom annotation formats do not have variant type, so we cannot match based on it). The code is now applied to VCF annotation only.

File: modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm (hunk 2 above)
Comment (nakib103) [reply modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm:345]: ah, sorry - I missed that it was an `if`, you can modify the next condition to have unless - 

`return 0 unless defined $ref_class && defined $vf_class && $ref_class eq $vf_class`;

the condition can only be true if both are defined and equal.

File: modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm (hunk 1 above)
Comment (nakib103) [reply modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:473]: That makes sense!

**Review by nakib103 — CHANGES_REQUESTED** [review]

**Review by nakib103 — APPROVED** [review]
LOTM !~
